### PR TITLE
Problem: Publisher forgets about send messages immediately

### PR DESCRIPTION
**Pull request by sappo**
Solution: Cache the send messages until a ACK is received and repeat
messages that have not been acked at a regular interval.

### CODE REVIEW

**Comment by sappo** [comment]
I'm not sure that I read the ACKs from the correct socket though.

**Comment by sappo** [comment]
Do we receive the ACKs on the publisher socket?

**Comment by sappo** [comment]
Also do we really need to repeat not acked messages? We are sending HEAD messages regularly so the stores could just ask for them

**Comment by sappo** [comment]
Okay, I'll remove the resend code

Am Sa., 2. Feb. 2019, 17:40 hat Doron Somech <notifications@github.com>
geschrieben:

**Comment by somdoron** [comment]
Let me know when to merge...

**Pull request merged**
