### PR TITLE
Problem: hash-table is not an efficient data structure to hold unacked msgs

### PR DESCRIPTION
**Pull request by somdoron**

### CODE REVIEW

**Comment by sappo** [comment]
Neat

**Comment by somdoron** [comment]
Yes, I'm getting around 500K messages a second (acked by a store) on my laptop now.

**Comment by sappo** [comment]
How much acks did you get before?

Doron Somech <notifications@github.com> schrieb am So., 12. Jan. 2020,
17:08:

**Comment by somdoron** [comment]
around 300K

**Comment by somdoron** [comment]
But that improved the rate publisher is sending and able to process acks

**Comment by sappo** [comment]
Now that's an impressive improvement :)

Doron Somech <notifications@github.com> schrieb am So., 12. Jan. 2020,
17:11:

**Pull request merged**
