### PR TITLE
 Problem: FETCH direct messages need priority over pubsub in order to fill the gap as soon as possible

### PR DESCRIPTION
**Pull request by somdoron**

### CODE REVIEW

**Comment by sappo** [comment]
How are direct messages prioritized? Cannot find the code that does the prioritization.

**Comment by somdoron** [comment]
I added review comments, see if it helps

**Comment by sappo** [comment]
Where do I find the review comments? Do you mean the commit comments because they did not help, sorry.

**Comment by somdoron** [comment]
I create two different subscribers, one subscribe to DIRECT MESSAGE and the other one to MSG.
https://github.com/somdoron/dafka/blob/9b07b72e66b6899cbc8a803e3f93d296862475cd/src/dafka_store.c#L339


To process the two subscribers, I'm using a while loop over the zsock_has_in for both subscribers
https://github.com/somdoron/dafka/blob/9b07b72e66b6899cbc8a803e3f93d296862475cd/src/dafka_store.c#L408

However, the loop always a process a message from the direct subscriber, if available, and only then from the regular subscriber.
https://github.com/somdoron/dafka/blob/9b07b72e66b6899cbc8a803e3f93d296862475cd/src/dafka_store.c#L415

**Pull request merged**
